### ISSUE TITLE
data-width="fit" cause error

### ISSUE THREAD

**Issue by dongepulango** [snapappointments/bootstrap-select-temp#27] opened 2018-03-21 12:23 UTC
![screen shot 2018-03-21 at 8 21 06 pm](https://user-images.githubusercontent.com/5156884/37709593-a9e931de-2d45-11e8-8f3d-7299696bdf58.png)

**Comment by caseyjhol** [comment] 2018-03-21 13:05
Duplicate of #17.

**Closed as completed by caseyjhol** 2018-03-21 13:05 UTC
