### ISSUE TITLE
When one item is selected in multiple select, text remains "Nothing selected"

### ISSUE THREAD

**Issue by mrlife** [snapappointments/bootstrap-select-temp#42] opened 2018-04-18 17:30 UTC
When 0 or 1 items are selected, the same "Nothing selected" text is displayed. After selecting a second item, then "2 items selected" is displayed.

Instead, when 1 item is selected, "1 item selected" should be displayed.

See the first dropdown under "Selected text format" in the documentation at this link: https://developer.snapappointments.com/bootstrap-select/examples/#selected-text-format

**Comment by jeffbeagley** [comment] 2018-04-18 17:34
Related item on previous repository, https://github.com/silviomoreto/bootstrap-select/pull/1933

**Comment by mrlife** [comment] 2018-04-18 18:07
@jeffbeagley Thanks for pointing that out. Any idea when v1.13 will be available?

**Comment by caseyjhol** [comment] 2018-04-18 19:00
Duplicate of #15. Fixed in https://github.com/snapappointments/bootstrap-select/commit/41ebe2220e82279200937c51ef5c8ffb90fe2637. Hoping to have v1.13.0 released today or tomorrow.

**Closed as completed by caseyjhol** 2018-04-18 19:00 UTC

**Comment by caseyjhol** [comment] 2018-04-19 22:14
Released in [v1.13.0](https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0)!
