### ISSUE TITLE
Bug: Characters like & are escaped to & amp; when used in titels

### ISSUE THREAD

**Issue by mikeploeger** [snapappointments/bootstrap-select-temp#70] opened 2018-06-14 02:09 UTC
Problem:
Optgroups with titles like "Bugs & Features" get escaped to "Bugs & amp; Features".

Solution:
Please dont escape the optgroup text by default or add an option to disable escaping.

Working Demo:
https://jsfiddle.net/dho62rmk/4/

<img width="265" alt="screen shot 2018-06-14 at 04 06 15" src="https://user-images.githubusercontent.com/8715351/41387697-9990c52e-6f88-11e8-8c76-45e25af0c538.png">

**Comment by caseyjhol** [comment] 2018-06-14 23:10
Duplicate of #51.

**Closed as completed by caseyjhol** 2018-06-14 23:10 UTC
