### ISSUE TITLE
Mobile not work

### ISSUE THREAD

**Issue by hugofabricio** [snapappointments/bootstrap-select-temp#66] opened 2018-05-29 12:41 UTC
When using active mobile, and clicking to open select, nothing happens. It does not display the default select options of the mobile phone and not even the dropdown it displays on the desktop.

**Comment by dirknilius** [comment] 2018-06-04 14:56
Confirmed. But only Safari/iOS is defect. Android works. Same as https://github.com/snapappointments/bootstrap-select/issues/55

**Comment by dirknilius** [comment] 2018-06-04 16:09
@hugofabricio You have to check the user agent by yourself when setting the mobile option. See https://developer.snapappointments.com/bootstrap-select/methods/#selectpickermobile

**Comment by caseyjhol** [comment] 2018-06-05 20:05
Duplicate of #55.

**Closed as completed by caseyjhol** 2018-06-05 20:05 UTC
